-- Create Sequences for data tables
CREATE SEQUENCE ADMINISTRATION_ROUTES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE APPLICATION_TEXT_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE ATTACHMENTS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE AUDIT_ENTRIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE BIOLOGICAL_IMPURITIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE CHEM_CLASSES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE CHEM_SUBCLASSES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE CODED_RISK_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE CITATIONS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE CITATION_SPECIALS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE CONTEXT_SENSTVE_CITATIONS_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE COUNTRIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE DIETARY_ALLOWANCES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE DOSAGE_FORMS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE DOSAGE_FORM_GROUPS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE DOSAGE_RANGE_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE EVIDENCE_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    
CREATE SEQUENCE EXTERNAL_MONOGRAPHS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;    

CREATE SEQUENCE FAMILIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE GENERA_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE GENERIC_TEXT_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE GEOGRAPHIC_AREAS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE homeopathic_dilutions_SEQ
    INCREMENT BY 1 START WITH 10 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE homeopathic_generic_texts_SEQ
    INCREMENT BY 1 START WITH 10 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE homeopathic_formulas_SEQ
    INCREMENT BY 1 START WITH 10 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE homeopathic_methofpreps_SEQ
    INCREMENT BY 1 START WITH 10 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE homeopathic_prep_Types_SEQ
    INCREMENT BY 1 START WITH 10 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE ICH_CLASSES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE IMPURITIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE INDICATIONS_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE INDICATION_TYPES_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE INGREDIENTS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE INGREDIENT_CATEGORIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE INGREDIENT_ROLES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE INGREDIENT_SOURCES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE INGREDIENT_SPECIALS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE MANUFACT_PROCESSES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE meddra_pref_terms_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE MONOGRAPHS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE MONOGRAPH_GROUPS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;




CREATE SEQUENCE MONOGRAPH_DIRECTS_FOR_USES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE MONOGRAPH_DOSES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE MONOGRAPH_DURATIONS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE MONOGRAPH_ENTRIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE monograph_dosecombs_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE monograph_phases_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
   
CREATE SEQUENCE monograph_preparations_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE monograph_risk_stmts_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE monograph_routeofadmins_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE monograph_types_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE mono_source_ingredients_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE mono_source_orgparts_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
        
CREATE SEQUENCE monograph_subingcombs_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
         
CREATE SEQUENCE monograph_subing_dosecombs_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    
CREATE SEQUENCE MONOGRAPH_SUBINGDOSES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE monograph_uses_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE NHP_CLASSIFICATIONS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE ORGANISMS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE ORGANISM_GROUPS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    
CREATE SEQUENCE ORGANISM_PARTS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE ORGANISM_PART_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE ORGANISM_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE ORGANISM_TYPE_GROUPS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE PERMISSIONS_SEQ
    INCREMENT BY 1 START WITH 10 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE preparation_types_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE preparation_type_groups_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE PRODUCT_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

-- Published Journal sequence starts high because information is
-- being loaded from an external source, before being loaded
-- by the Ingredients loader.
CREATE SEQUENCE PUBLISHED_JOURNALS_SEQ
    INCREMENT BY 1 START WITH 25000 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE PURPOSES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE QUALIFIED_SYNONYMS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE QUALITY_TOLERANCE_MODELS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE RATIONALES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE RECOMMENDED_DIETARY_ALLO_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE REFS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE REGISTRY_ENTRIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE RESTRICTIONS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE RESTRICTION_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE RISKS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE risk_types_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE ROLE_SPECIALS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE solvents_seq
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
CREATE SEQUENCE SPECIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE SUBINGREDIENTS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE subtaxa_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE sub_population_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE SYNONYMS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE TAXA_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE TEST_CATEGORIES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE TEST_METHODS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE TEST_METHOD_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE TEST_METHOD_SUBTYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE TEST_SPECIFICATIONS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE text_mono_srcmaterials_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE trad_paradigms_seq 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE UNITS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE UNITS_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE USER_ACCOUNTS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    
CREATE SEQUENCE USE_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    
CREATE SEQUENCE USER_ROLES_SEQ
    INCREMENT BY 1 START WITH 10 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    
CREATE SEQUENCE PREPARATION_RULES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    
CREATE SEQUENCE APPLICATION_TYPES_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;    
    
CREATE SEQUENCE DOSAGE_UNITS_SEQ
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;    
    
CREATE SEQUENCE PROVINCES_STATES_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    
CREATE SEQUENCE common_terms_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;

CREATE SEQUENCE common_term_types_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;    
    
CREATE SEQUENCE standard_grade_refs_SEQ 
    INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 
    NOCYCLE 
    NOCACHE NOORDER;
    