-----------------------------------
--patch #07
-- date: 2019/09/19
-- fixes: V_MONO_INGREDIENT_USE
--        X$SUB_POULATION data set
-- log: patch_07.log
----------------------------------
spool patch_07.log
prompt Patch 07
prompt update V_MONO_INGREDIENT_USES
create or replace force view
v_mono_ingredient_uses
as
select t.mono_code, d.ingredient_id, d.ingred_name_eng, t.use_code, t.use_decode_eng, t.use_decode_fr 
  from v_assessment_doses d,
       v_assessment_dose_use t
 where d.assessment_dose_id = t.assessment_dose_id
--   and d.ingredient_id not in (select subingredient_id from v_mono_subingreds)
 union
select t2.mono_code, s.ingred_id ingredient_id, s.ingred_nhpid_name, t2.use_code, t2.use_decode_eng, t2.use_decode_fr
  from v_mono_subingreds s, 
       v_assessment_doses d2, 
       v_assessment_dose_use t2
 where s.subingredient_id = d2.ingredient_id
   and s.mono_code = d2.mono_code
   and t2.assessment_dose_id = d2.assessment_dose_id
;

prompt update X$SUB_POPULATION data set
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (12, 'SP72', 51, 'ADU10', 'Adolescents and adults', 10, NULL, 169, 0, NULL, NULL, 'Adolescents and adults 10 year(s) and older', NULL, NULL, 14, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (13, 'SP52', 52, 'ADU12', 'Adolescents and adults', 12, NULL, 169, 0, NULL, NULL, 'Adolescents and adults 12 year(s) and older', NULL, 'y', 13, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (15, 'SP67', 17, 'ADU13', 'Adolescents and adults', 13, NULL, 169, 0, NULL, NULL, 'Adolescents and adults 13 year(s) and older', NULL, 'y', 11, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (16, 'SP107', NULL, NULL, 'Adolescents and adults', 13, NULL, 169, 2, 'Breastfeeding', 'Allaitantes', 'Breastfeeding Adolescents and adults Females 13 year(s) and older', '13-200 an(s) Femmes allaitantes', NULL, 11, 1);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (30, 'SP409', NULL, NULL, 'Adolescents and adults', 14, NULL, 169, 2, NULL, NULL, 'Adolescents and adults Females 14 year(s) and older', NULL, NULL, 17, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (31, 'SP132', NULL, NULL, 'Adolescents and adults', 14, NULL, 169, 2, 'Peri or postmenopausal', 'Péri et postménopausées', 'Peri or postmenopausal Adolescents and adults Females 14 year(s) and older', '14-200 an(s) Femmes péri ou post-ménopausées', NULL, 17, 4);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (32, 'SP16', 16, 'ADU14', 'Adolescents and adults', 14, NULL, 169, 0, NULL, NULL, 'Adolescents and adults 14 year(s) and older', NULL, 'y', 17, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (33, 'SP408', NULL, NULL, 'Adolescents and adults', 14, NULL, 169, 1, NULL, NULL, 'Adolescents and adults Males 14 year(s) and older', NULL, NULL, 17, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (34, 'SP113', NULL, NULL, 'Adolescents and adults', 14, NULL, 169, 2, 'Pregnant', 'Enceintes', 'Pregnant Adolescents and adults Females 14 year(s) and older', '14-200 an(s) Femmes enceintes', NULL, 17, 6);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (36, 'SP66', 2, 'ADU15', 'Adolescents and adults', 15, NULL, 169, 0, NULL, NULL, 'Adolescents and adults 15 year(s) and older', NULL, 'y', 18, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (49, 'SP602', NULL, NULL, 'Adults', 18, NULL, 169, 2, 'Breastfeeding', 'Allaitantes', 'Breastfeeding Adults Females 18 year(s) and older', '18-00 an(s) Femmes allaitantes', NULL, 23, 1);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (50, 'SP51', NULL, NULL, 'Adults', 18, NULL, 169, 2, 'Menopausal and postmenopausal', 'Ménopausées et postménopausées', 'Menopausal and postmenopausal Adults Females 18 year(s) and older', NULL, NULL, 23, 3);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (51, 'SP60', NULL, NULL, 'Adults', 18, NULL, 169, 2, 'Pregnant and breastfeeding', 'Enceintes et allaitantes', 'Pregnant and breastfeeding Adults Females 18 year(s) and older', '18-200 an(s) Femmes enceintes et allaitantes', NULL, 23, 7);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (52, 'SP53', NULL, NULL, 'Adults', 18, NULL, 169, 1, NULL, NULL, 'Adults Males 18 year(s) and older', NULL, NULL, 23, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (53, 'SP61', 76, 'ADUM_18', 'Adults', 18, NULL, 169, 0, NULL, NULL, 'Adults 18 year(s) and older', NULL, NULL, 23, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (54, 'SP124', NULL, NULL, 'Adults', 18, NULL, 169, 2, 'Premenopausal', 'Préménopausées', 'Premenopausal Adults Females 18 year(s) and older', '18-200 an(s) Femmes pré-ménopausées', NULL, 23, 9);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (55, 'SP54', NULL, NULL, 'Adults', 18, NULL, 169, 2, NULL, NULL, 'Adults Females 18 year(s) and older', NULL, NULL, 23, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (56, 'SP18', NULL, NULL, 'Adults', 18, NULL, 169, 2, 'Postmenopausal', 'Enceintes', 'Postmenopausal Adults Females 18 year(s) and older', '18-200 an(s) Femmes post-ménopausées', NULL, 23, 5);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (57, 'SP17', NULL, NULL, 'Adults', 18, NULL, 169, 2, 'Menopausal', 'Enceintes', 'Menopausal Adults Females 18 year(s) and older', NULL, NULL, 23, 2);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (58, 'SP601', NULL, NULL, 'Adults', 18, NULL, 169, 2, 'Pregnant', 'Enceintes', 'Pregnant Adults Females 18 year(s) and older', '18-00 an(s) Femmes enceintes', NULL, 23, 6);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (73, 'SP42', 42, 'MAL', 'Adults', 19, NULL, 169, 1, NULL, NULL, 'Adults Males 19 year(s) and older', NULL, NULL, 27, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (74, 'SP4', 56, 'ADU', 'Adults', 19, NULL, 169, 0, NULL, NULL, 'Adults 19 year(s) and older', NULL, 'y', 27, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (75, 'SP43', 72, 'FEM', 'Adults', 19, NULL, 169, 2, NULL, NULL, 'Adults Females 19 year(s) and older', NULL, NULL, 27, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (76, 'SP431', NULL, NULL, 'Adults', 19, NULL, 169, 2, 'Pregnant and breastfeeding', 'Enceintes et allaitantes', 'Pregnant and breastfeeding Adults Females 19 year(s) and older', NULL, NULL, 27, 7);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (81, 'SP300', NULL, NULL, 'Adults', 31, NULL, 169, 1, NULL, NULL, 'Adults Males 31 year(s) and older', NULL, NULL, 29, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (82, 'SP301', NULL, NULL, 'Adults', 31, NULL, 169, 2, NULL, NULL, 'Adults Females 31 year(s) and older', NULL, NULL, 29, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (87, 'SP79', NULL, NULL, 'Adults', 51, NULL, 169, 2, NULL, NULL, 'Adults Females 51 year(s) and older', NULL, NULL, 32, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (88, 'SP77', NULL, NULL, 'Adults', 51, NULL, 169, 1, NULL, NULL, 'Adults Males 51 year(s) and older', NULL, NULL, 32, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (89, 'SP28', 28, 'A_51', 'Adults', 51, NULL, 169, 0, NULL, NULL, 'Adults 51 year(s) and older', NULL, NULL, 32, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (90, 'SP95', 68, 'FEM_70', 'Adults', 70, NULL, 169, 2, NULL, NULL, 'Adults Females 70 year(s) and older', NULL, NULL, 31, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (91, 'SP12', 31, 'A_70', 'Adults', 70, NULL, 169, 0, NULL, NULL, 'Adults 70 year(s) and older', NULL, NULL, 31, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (92, 'SP91', 74, 'MAL_70', 'Adults', 70, NULL, 169, 1, NULL, NULL, 'Adults Males 70 year(s) and older', NULL, NULL, 31, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (93, 'SP103y', NULL, NULL, 'Adults', 71, NULL, 169, 0, NULL, NULL, 'Adults 71 year(s) and older', NULL, NULL, 26, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (94, 'SP103', NULL, NULL, 'Adults', 71, NULL, 169, 0, NULL, NULL, 'Adults 71 year(s) and older', NULL, NULL, 26, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (95, 'SP136', NULL, NULL, 'Adults', 71, NULL, 169, 2, 'Peri or postmenopausal', 'Péri et postménopausées', 'Peri or postmenopausal Adults Females 71 year(s) and older', NULL, NULL, 26, 4);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (96, 'SP103x', NULL, NULL, 'Adults', 71, NULL, 169, 0, NULL, NULL, 'Adults 71 year(s) and older', NULL, NULL, 26, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (131, 'SP20', 14, 'ADU1', 'Children, adolescents, and adults', 1, NULL, 169, 0, NULL, NULL, 'Children, adolescents, and adults 1 year(s) and older', NULL, NULL, 69, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (132, 'SP74', NULL, NULL, 'Children, adolescents, and adults', 11, NULL, 169, 0, NULL, NULL, 'Children, adolescents, and adults 11 year(s) and older', NULL, NULL, 63, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (134, 'SP68', 10, 'ADU2', 'Children, adolescents, and adults', 2, NULL, 169, 0, NULL, NULL, 'Children, adolescents, and adults 2 year(s) and older', NULL, NULL, 68, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (137, 'SP85', 1, 'ADU6', 'Children, adolescents, and adults', 6, NULL, 169, 0, NULL, NULL, 'Children, adolescents, and adults 6 year(s) and older', NULL, NULL, 65, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (138, 'SP305', NULL, NULL, 'Children, adolescents, and adults', 9, NULL, 169, 0, NULL, NULL, 'Children, adolescents, and adults 9 year(s) and older', NULL, NULL, 64, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (167, 'SP101', NULL, NULL, 'Infants, children, adolescents, and adults', 0, NULL, 169, 0, NULL, NULL, 'Infants, children, adolescents, and adults 0 year(s) and older', NULL, NULL, 95, NULL);
INSERT INTO X$SUB_POPULATION T (SUB_POP_ID, SUB_POP_CODE, NHPID_SUBPOP_ID, NHPID_CODE, AGE_GROUP, AGE_MIN, AGE_MAX, AGE_UNIT_ID, SEX_ID, SUB_POP_CONDITION, SUB_POP_CONDITION_FR, SUB_POP_DECODE, SUB_POP_DECODE_FR, PREFERRED, AGE_GROUP_ID, CONDITION_ID)
  VALUES (168, 'SP307', NULL, NULL, 'Infants, children, adolescents, and adults', 0.5, NULL, 169, 0, NULL, NULL, 'Infants, children, adolescents, and adults 0.5 year(s) and older', NULL, NULL, 96, NULL);
COMMIT;

prompt Done
spool off

