
package ca.gc.hc.webservice;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IngredientService", targetNamespace = "http://ingredient.webservice.nhpd.hc.gc.ca/", wsdlLocation = "https://nnhpddevdemo.canadaeast.cloudapp.azure.com/IngredientAndMonographWS/IngredientService?wsdl")
@HandlerChain(file = "handler-chain.xml")
public class IngredientService_Service extends Service {

	private final static URL INGREDIENTSERVICE_WSDL_LOCATION;
	private final static WebServiceException INGREDIENTSERVICE_EXCEPTION;
	private final static QName INGREDIENTSERVICE_QNAME = new QName("http://ingredient.webservice.nhpd.hc.gc.ca/",
			"IngredientService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(
					"https://nnhpddevdemo.canadaeast.cloudapp.azure.com/IngredientAndMonographWS/IngredientService?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		INGREDIENTSERVICE_WSDL_LOCATION = url;
		INGREDIENTSERVICE_EXCEPTION = e;
	}

	public IngredientService_Service() {
		super(__getWsdlLocation(), INGREDIENTSERVICE_QNAME);
	}

	public IngredientService_Service(WebServiceFeature... features) {
		super(__getWsdlLocation(), INGREDIENTSERVICE_QNAME, features);
	}

	public IngredientService_Service(URL wsdlLocation) {
		super(wsdlLocation, INGREDIENTSERVICE_QNAME);
	}

	public IngredientService_Service(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, INGREDIENTSERVICE_QNAME, features);
	}

	public IngredientService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IngredientService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns IngredientService
	 */
	@WebEndpoint(name = "IngredientServicePort")
	public IngredientService getIngredientServicePort() {
		return super.getPort(new QName("http://ingredient.webservice.nhpd.hc.gc.ca/", "IngredientServicePort"),
				IngredientService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on
	 *            the proxy. Supported features not in the <code>features</code>
	 *            parameter will have their default values.
	 * @return returns IngredientService
	 */
	@WebEndpoint(name = "IngredientServicePort")
	public IngredientService getIngredientServicePort(WebServiceFeature... features) {
		return super.getPort(new QName("http://ingredient.webservice.nhpd.hc.gc.ca/", "IngredientServicePort"),
				IngredientService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (INGREDIENTSERVICE_EXCEPTION != null) {
			throw INGREDIENTSERVICE_EXCEPTION;
		}
		return INGREDIENTSERVICE_WSDL_LOCATION;
	}

}
