package ca.gc.hc.nhpd.util;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.proxy.EntityNotFoundDelegate;
import java.io.Serializable;

/**
 * This class is called when an object can't be found by hibernate.  It 
 * was implemented to reduce the stack trace generated by hibernate in 
 * these conditions.
 * 
 * @author GEBRUNET
 */

public class HibernateEntityNotFound implements EntityNotFoundDelegate {

	private static Log log = LogFactory.getLog(HibernateEntityNotFound.class);
	
	private static String ERROR_MESSAGE_START = "No row with the given identifier exists: [";
	private static String ERROR_MESSAGE_MIDDLE = "#";
	private static String ERROR_MESSAGE_END = "]";
	
	public void handleEntityNotFound(String entityName, Serializable id) {
		StringBuilder sb = new StringBuilder();
		sb.append(ERROR_MESSAGE_START).append(entityName);
		sb.append(ERROR_MESSAGE_MIDDLE).append(id);
		sb.append(ERROR_MESSAGE_END);
		log.warn(sb.toString());
	};
	
}
