pipeline {
    agent any
    tools {
        maven 'Maven 3.3.3'
        jdk 'Java 7'
    }
    stages {
        stage ('Initialize1') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
                sh 'mvn clean deploy -Dmaven.test.skip=true' 
            }
        }
    }
}