version: '3'
services:
    webapp:
        image: registry.gitlab.com/asolism/cyclops/webapp:latest
        restart: always
#        image: webapp
        ports:
            - 5000:5000
            - 8000:8000
        environment:
            MAPI_URL: http://mapi:9000
    mapi:
        image: registry.gitlab.com/asolism/cyclops/mapi:latest
        restart: always
#       image: mapi
        expose:
            - 9000
        ports:
            - 9000:9000
        volumes:
            - ./data:/data
        environment:
            # MONGO_MAPI_URL: "mongodb-imagecache.default.svc.cluster.local:27017"
            MONGO_MAPI_USER: cyclops
            MONGO_URL: mongo
            MONGO_MAPI_DB: images
            MONGO_MAPI_PASS: "temporary_password"
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_MAPI_USER: cyclops
            MONGO_MAPI_DB: images
            MONGO_MAPI_PASS: "temporary_password"
        expose:
            - 27017
        #ports:
        #    - 27017:27017
        volumes:
            - ./images_db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
            #- ./images_db/data:/data/db
